In [1]:
import numpy as np

In [2]:
i = 4
"w" + str(i)

'w4'

In [3]:
f"w{i}"

'w4'

In [4]:
a = [2,3,4]
[4]+a
a

[2, 3, 4]

In [5]:
[4, a]

[4, [2, 3, 4]]

In [6]:
np.hstack((4,a))

array([4, 2, 3, 4])

In [16]:
sizes = [784, 15, 10]
W = [np.random.normal(loc=0.0, scale=0.01, size=(j, k)) for j, k in zip(sizes[1:], sizes[:-1])]
[w.shape for w in W]

[(15, 784), (10, 15)]

In [91]:
a = np.random.randint(10, size=(15,))
a

array([0, 4, 0, 8, 6, 7, 4, 9, 3, 6, 1, 2, 2, 2, 7])

In [109]:
i = np.random.randint(len(a))
i

13

In [110]:
y = a[i]
y

2

In [111]:
0.25 < (i+1) / len(a) < 0.75

False

In [105]:
i+1

7

In [104]:
len(a)

15

In [106]:
(i+1) / len(a)

0.4666666666666667

In [114]:
a[:i]

array([0, 4, 0, 8, 6, 7, 4, 9, 3, 6, 1, 2, 2])

In [115]:
a[i+1:]

array([7])

In [113]:
np.concatenate((a[:i], [y], a[i+1:]))

array([0, 4, 0, 8, 6, 7, 4, 9, 3, 6, 1, 2, 2, 2, 7])

In [220]:
def randQS(L):
    
    L = np.array(L)
    n = len(L)
    
    if n == 0:
        return np.array([])
    if n == 1:
        return L
    if n == 2:
        if L[0] < L[1]:
            return L
        else:
            return np.concatenate(([L[1]], [L[0]]))
    if n == 3:
        i = 1
    if n == 4:
        i = 1    
    else:
        i = -1
        k = 0
        while k < 4:
            if 0.25 < (i+1) / n < 0.75:
                i = np.random.randint(n)
                continue
            break

    y = L[i]
    
    S = np.concatenate((L[:i], L[i+1:]))
    S1, S2 = [], []
    
    for j in S:
        if S[j] < y:
            S1.append[L[j]]
        else:
            S2.append[L[j]]
    
    return np.concatenate(randQS(S1), [y], randQS(S2))

In [221]:
L = np.random.randint(10, size=(3,))
L

array([5, 3, 9])

In [222]:
randQS(L)

IndexError: index 5 is out of bounds for axis 0 with size 5

In [229]:
for i in range(5, 2, -1):
    print(i)

5
4
3


In [230]:
a = []
a[1] = 4

IndexError: list assignment index out of range