In [1]:
import numpy as np

In [2]:
a = [1,4,3,2]
c = np.argsort(a)
c

array([0, 3, 2, 1], dtype=int64)

In [3]:
a

[1, 4, 3, 2]

In [4]:
b = np.array([5,6,7,8])
b[np.argsort(b)]

array([5, 6, 7, 8])

In [5]:
a = np.array([3,1,4,2,1,3])
values, counts = np.unique(a, return_counts=True)
print(values, counts)
index = np.argmax(counts)
values[index]
print(index, values[index])

[1 2 3 4] [2 1 2 1]
0 1


In [6]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
b = np.arange(3,15).reshape(4,3)
b

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [8]:
np.sqrt(np.diag(a @ a.T).reshape(-1,1) -2*a @ b.T\
            + np.diag(b @ b.T).reshape(1,-1))

array([[ 5.19615242, 10.39230485, 15.58845727, 20.78460969],
       [ 0.        ,  5.19615242, 10.39230485, 15.58845727],
       [ 5.19615242,  0.        ,  5.19615242, 10.39230485]])

In [9]:
a = np.arange(100).reshape(10,-1)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [10]:
a.shape

(10, 10)

In [11]:
b = np.array_split(a, 5)
b

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]]),
 array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]]),
 array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79]]),
 array([[80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])]

In [12]:
b[0].shape

(2, 10)

In [13]:
for fold in range(5):
    print(np.concatenate((b[:fold] + b[fold+1:])))

[[20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [80 81

In [14]:
np.concatenate((b[0],b[1]))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [15]:
# Split the data into train, val, and test sets. In addition we will
# create a small development set as a subset of the training data;
# we can use this for development so our code runs faster.
num_training = 49000
num_validation = 1000
num_test = 1000
num_dev = 500

# Our validation set will be num_validation points from the original
# training set.
mask = range(num_training, num_training + num_validation)
print(mask)



range(49000, 50000)


In [16]:
a = np.arange(80).reshape(8,-1)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79]])

In [17]:
b  = np.random.choice(9, size=8)
b

array([5, 8, 4, 2, 8, 8, 3, 6])

In [18]:
c = a[np.arange(a.shape[0]), b].reshape(-1, 1)
c

array([[ 5],
       [18],
       [24],
       [32],
       [48],
       [58],
       [63],
       [76]])

In [19]:
margins = np.maximum(0, a - c + 1)
margins

array([[0, 0, 0, 0, 0, 1, 2, 3, 4, 5],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 2],
       [0, 0, 0, 0, 1, 2, 3, 4, 5, 6],
       [0, 0, 1, 2, 3, 4, 5, 6, 7, 8],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 2],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 2],
       [0, 0, 0, 1, 2, 3, 4, 5, 6, 7],
       [0, 0, 0, 0, 0, 0, 1, 2, 3, 4]])

In [20]:
margins[np.arange(a.shape[0]), b] = 0
margins

array([[0, 0, 0, 0, 0, 0, 2, 3, 4, 5],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 2],
       [0, 0, 0, 0, 0, 2, 3, 4, 5, 6],
       [0, 0, 0, 2, 3, 4, 5, 6, 7, 8],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 2],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 2],
       [0, 0, 0, 0, 2, 3, 4, 5, 6, 7],
       [0, 0, 0, 0, 0, 0, 0, 2, 3, 4]])

In [21]:
d = np.where(margins > 0, 1, 0)
d

array([[0, 0, 0, 0, 0, 0, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 1, 1, 1, 1, 1],
       [0, 0, 0, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 1, 1, 1]])

In [22]:
X  = np.random.choice(9, size=(8,3))
X

array([[2, 2, 6],
       [5, 0, 2],
       [5, 1, 0],
       [3, 5, 6],
       [1, 7, 4],
       [2, 0, 2],
       [3, 0, 7],
       [4, 3, 4]])

In [23]:
dW = np.zeros((3,10))
dW

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [24]:
f = d.sum(axis=1)
f

array([4, 1, 5, 7, 1, 1, 6, 3])

In [25]:
d[np.arange(d.shape[0]), b] = -f
d

array([[ 0,  0,  0,  0,  0, -4,  1,  1,  1,  1],
       [ 0,  0,  0,  0,  0,  0,  0,  0, -1,  1],
       [ 0,  0,  0,  0, -5,  1,  1,  1,  1,  1],
       [ 0,  0, -7,  1,  1,  1,  1,  1,  1,  1],
       [ 0,  0,  0,  0,  0,  0,  0,  0, -1,  1],
       [ 0,  0,  0,  0,  0,  0,  0,  0, -1,  1],
       [ 0,  0,  0, -6,  1,  1,  1,  1,  1,  1],
       [ 0,  0,  0,  0,  0,  0, -3,  1,  1,  1]])

In [26]:
X.T

array([[2, 5, 5, 3, 1, 2, 3, 4],
       [2, 0, 1, 5, 7, 0, 0, 3],
       [6, 2, 0, 6, 4, 2, 7, 4]])

In [27]:
X.T @ d

array([[  0,   0, -21, -15, -19,   3,   1,  17,   9,  25],
       [  0,   0, -35,   5,   0,  -2,  -1,  11,   4,  18],
       [  0,   0, -42, -36,  13, -11,   7,  23,  15,  31]])

In [28]:
f = d.sum(axis=1)
f

array([0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
e = np.zeros_like(d)
e

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [30]:
e[np.arange(e.shape[0]), b] = -f
e

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [31]:
G  = np.random.choice(9, size=(8,3))
G

array([[2, 3, 8],
       [1, 4, 3],
       [2, 2, 8],
       [5, 8, 2],
       [2, 6, 6],
       [2, 2, 3],
       [3, 5, 4],
       [5, 5, 2]])

In [32]:
np.argmax(G, axis=1)

array([2, 1, 2, 1, 1, 2, 1, 0], dtype=int64)

In [33]:
np.max(G, axis=1)

array([8, 4, 8, 8, 6, 3, 5, 5])

In [34]:
np.sum(G, axis=1)

array([13,  8, 12, 15, 14,  7, 12, 12])

In [35]:
a = np.arange(80).reshape(8,-1)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79]])

In [36]:
b  = np.random.choice(9, size=8)
b

array([5, 5, 6, 7, 4, 0, 0, 1])

In [37]:
c = a[np.arange(a.shape[0]), b].reshape(-1, 1)
c

array([[ 5],
       [15],
       [26],
       [37],
       [44],
       [50],
       [60],
       [71]])

In [38]:
x = np.random.choice(range(-9,10), size=(5,3))
x

array([[ 6,  9, -6],
       [-5,  6, -4],
       [ 1,  9, -9],
       [ 3, -3,  3],
       [-4, -7,  6]])

In [39]:
w = np.random.choice(range(-9,10), size=(3,2))
w

array([[ 2, -1],
       [-8, -5],
       [-7,  8]])

In [40]:
b = np.random.choice(range(-9,10), size=(2,))
b

array([-9,  9])

In [41]:
x @ w

array([[ -18,  -99],
       [ -30,  -57],
       [  -7, -118],
       [   9,   36],
       [   6,   87]])

In [42]:
z = x @ w + b
z

array([[ -27,  -90],
       [ -39,  -48],
       [ -16, -109],
       [   0,   45],
       [  -3,   96]])

In [43]:
z.sum(axis=0)

array([ -85, -106])

In [44]:
x = np.random.choice(range(-9,10), size=(5,3))
x

array([[ 8,  9, -8],
       [-3,  4,  8],
       [-1,  5,  5],
       [ 2,  0,  3],
       [-2, -2,  1]])

In [45]:
np.maximum(0,x)

array([[8, 9, 0],
       [0, 4, 8],
       [0, 5, 5],
       [2, 0, 3],
       [0, 0, 1]])

In [46]:
rng = np.random.default_rng(seed=42)
dout = rng.random((5, 3)) - 0.5
dout

array([[ 0.27395605, -0.06112156,  0.35859792],
       [ 0.19736803, -0.40582265,  0.47562235],
       [ 0.2611397 ,  0.28606431, -0.37188637],
       [-0.04961406, -0.12920198,  0.42676499],
       [ 0.14386512,  0.32276161, -0.0565858 ]])

In [47]:
np.where(x>0, dout, 0)

array([[ 0.27395605, -0.06112156,  0.        ],
       [ 0.        , -0.40582265,  0.47562235],
       [ 0.        ,  0.28606431, -0.37188637],
       [-0.04961406,  0.        ,  0.42676499],
       [ 0.        ,  0.        , -0.0565858 ]])

In [48]:
10 // 3

3

In [49]:
p = 0.7
np.sum(np.random.rand(10,10) < p)

73

In [50]:
np.random.uniform(-5,5)

1.2231733566893048

In [51]:
np.arange(-5,5)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [52]:
reg = [10**k for k in range(-5,5)]
reg

[1e-05, 0.0001, 0.001, 0.01, 0.1, 1, 10, 100, 1000, 10000]

In [53]:
max_count = 20
for count in range(max_count):
    reg = 10**np.random.uniform(-4,0)
    lr = 10**np.random.uniform(-3,-4)
    print(reg, lr)

0.4606708266997721 0.0009095296249767528
0.06951240104436429 0.0007763197033743731
0.07130342384584955 0.0001232408829312297
0.0005947303788468648 0.00011525986044345732
0.0011775242254151049 0.0005691167464355559
0.15013475541224444 0.00013686820384540164
0.0033779789849961214 0.00043269118411870294
0.019725231268334288 0.0004978485860478612
0.7124989320939966 0.00020522457106666558
0.0016983798575008206 0.0005916080248634139
0.0010863159693244267 0.0003519219535558775
0.000601577627731723 0.00028320211193965885
0.13482708991650283 0.0005402252829530882
0.020846367822514315 0.0003172440159275265
0.11196235501406544 0.0002992153204323708
0.00016646371952527353 0.0003177033765518295
0.0008384491603352659 0.00015872156975743905
0.06728094202186406 0.00016356919186992448
0.0002565468974772741 0.00010509278089213991
0.0027301678548775706 0.00018075755451965193


In [54]:
import numpy as np
from cs231n.data_utils import load_CIFAR10
import matplotlib.pyplot as plt
from cs231n.classifiers.fc_net import *
from cs231n.data_utils import get_CIFAR10_data
from cs231n.gradient_check import eval_numerical_gradient, eval_numerical_gradient_array
from cs231n.solver import Solver

%load_ext autoreload
%autoreload 2

data = get_CIFAR10_data()
for k, v in list(data.items()):
  print(('%s: ' % k, v.shape))

('X_train: ', (49000, 3, 32, 32))
('y_train: ', (49000,))
('X_val: ', (1000, 3, 32, 32))
('y_val: ', (1000,))
('X_test: ', (1000, 3, 32, 32))
('y_test: ', (1000,))


In [55]:
input_size = 32 * 32 * 3
hidden_size = 50
num_classes = 10

# data['X_train'] = data['X_train'][:20]
# data['y_train'] = data['y_train'][:20]

learning_rate = 3e-3
reg = 100
lr_decay = 0.9
num_epochs = 10
batch_size = 100

max_count = 10
history = []
for count in range(max_count):
    reg = 10**np.random.uniform(-4,0)
    lr = 10**np.random.uniform(-3,-6)
    
    model = TwoLayerNet(input_size, hidden_size, num_classes, reg=reg)

    solver = Solver(model, data,
                    update_rule='sgd',
                    optim_config={
                        'learning_rate': lr,
                        },
                    lr_decay=lr_decay,
                    num_epochs=num_epochs,
                    batch_size=batch_size,
                    print_every = 100,
                    verbose=False)

    solver.train()
    history.append((solver.best_val_acc, lr, reg))
    print(f"# {count}: val_acc: {solver.best_val_acc}, lr: {lr}, reg: {reg}")

history.sort(reverse=True, key=lambda a: a[0])
for k in history[:10]:
    print(k)

# 0: val_acc: 0.212, lr: 2.6440980107426116e-06, reg: 0.01645215543852264
# 1: val_acc: 0.455, lr: 9.864852958323932e-05, reg: 0.00013500459925051722
# 2: val_acc: 0.265, lr: 9.257305965405148e-06, reg: 0.37219758089456734
# 3: val_acc: 0.214, lr: 4.138557493455165e-06, reg: 0.17530190616583052
# 4: val_acc: 0.373, lr: 3.1695994035045825e-05, reg: 0.00037531038800646486
# 5: val_acc: 0.498, lr: 0.0008499595801801215, reg: 0.0001235101741765082
# 6: val_acc: 0.209, lr: 3.396955944481668e-06, reg: 0.4077350758058836
# 7: val_acc: 0.177, lr: 1.7777786146646457e-06, reg: 0.01217792054035219
# 8: val_acc: 0.184, lr: 1.2729208197016393e-06, reg: 0.030530131254570006
# 9: val_acc: 0.477, lr: 0.0002278945997079679, reg: 0.00021669998133528912
(0.498, 0.0008499595801801215, 0.0001235101741765082)
(0.477, 0.0002278945997079679, 0.00021669998133528912)
(0.455, 9.864852958323932e-05, 0.00013500459925051722)
(0.373, 3.1695994035045825e-05, 0.00037531038800646486)
(0.265, 9.257305965405148e-06, 0.37